name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  create_tag_and_release_note:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: Get version from manifest.json
        run: |
          VERSION=$(jq -r '.version' dist/manifest.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Create tag and release note
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2
        with:
          target_commitish: main
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          generate_release_notes: true

  upload_build_to_store:
    needs: create_tag_and_release_note
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24.17.0
          cache: npm
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        name: Install npm packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Zip
        run: zip -r dist.zip dist
      - name: Upload to Chrome Web Store
        uses: mnao305/chrome-extension-upload@4008e29e13c144d0f6725462cbd49b7c291b4928 # v5.0.0
        with:
          file-path: dist.zip
          extension-id: ${{ secrets.EXTENSION_ID }}
          client-id: ${{ secrets.PUBLISH_CLIENT_ID }}
          client-secret: ${{ secrets.PUBLISH_CLIENT_SECRET }}
          refresh-token: ${{ secrets.PUBLISH_REFRESH_TOKEN }}
          publish: false
